export default function() {
	return {
		act_mode: 'add',
		title: '',
		tile_eng: '',
		company_name: '',
		company_engname: '',
		customer_name: '',
		customer_engname: '',
		customer_brandname: '',
		customer_engbrandname: '',
		contact_name: '',
		contact_phone: '',
		contact_email: '',
		main_type: '選擇參加類別',
		sub_type: '選擇參加項目',
		summary: '',
		registration_file: '',
		exposition_file: '',
		case_film_url: '',
		list_customer_name: '',
		list_partner_name: '',
		list_thirdparty_name: '',
		coremember: [
			{
				company_name: '',
				name: '',
				job_title: '',
				email:'',
			},
		],
		s_date: '1900-01-01',
		e_date: '1900-01-01',
		online: '',
		scope: '參賽作品應用範圍',
		apply_country: [
			{ id: 0, name: 'Australia', active: false },
			{ id: 1, name: 'Brazil', active: false },
			{ id: 2, name: 'Canada', active: false },
			{ id: 3, name: 'France', active: false },
			{ id: 4, name: 'Greece', active: false },
			{ id: 5, name: 'Hong Kong', active: false },
			{ id: 6, name: 'India', active: false },
			{ id: 7, name: 'Italy', active: false },
			{ id: 8, name: 'Japan', active: false },
			{ id: 9, name: 'Korea', active: false },
			{ id: 10, name: 'Macau', active: false },
			{ id: 11, name: 'Mainland China', active: false },
			{ id: 12, name: 'Malaysia', active: false },
			{ id: 13, name: 'New Zealand', active: false },
			{ id: 14, name: 'Russia', active: false },
			{ id: 15, name: 'Singapore', active: false },
			{ id: 16, name: 'Spain', active: false },
			{ id: 17, name: 'Taiwan', active: false },
			{ id: 18, name: 'Thailand', active: false },
			{ id: 19, name: 'UK', active: false },
			{ id: 20, name: 'United Arab Emirates', active: false },
			{ id: 21, name: 'USA', active: false },
			{ id: 22, name: 'Others', active: false },
		],
	};
}

// export default { Form };
